### ISSUE TITLE
Os eventos de registro de voz usam user.Username ao inves de member.DisplayName()

### ISSUE THREAD

**Issue by vcaldo** [Vale-Tudo-Devs/cerverox9#9]
e por esse motivo as mensagens de entrou e saiu ficam com o user name ao inves do display name. Implementar member.DisplayName() na função `[LogVoiceEvents()]`(https://github.com/vcaldo/cerverox9/blob/7857210272d9da7453b70e18fb3f92b2efc7182a/discord/pkg/models/models.go#L81-L98)

**Comment by vcaldo** [comment]
Esse ticket pode ser feito ao mesmo tempo que esse https://github.com/vcaldo/cerverox9/issues/12

**Comment by Nogueira94** [comment]
Fixed
